pets_service:
  base: 'https://locallhost.com'
  endpoints:
    register_pet:
      path: '/pet'
    get_pets:
      path: '/owner/{owner_id}'
      query_params:
        offset: 0
        limit: 100
    get_pet_by_id:
      path: '/pet/{pet_id}'

treatments_service:
  base: 'https://locallhost.com'

users_service:
  base: 'https://locallhost.com'
